server:
  port: 9998
  servlet:
    context-path: /wgcloud-agent
spring:
  application:
    name: wgcloud-agent
#Log file output path
logging:
  file:
    path: ./log

#Custom configuration parameter
base:
  #wgcloud-Server access address
  serverUrl: http://localhost:9999
  #This machine IP, do not use localhost or 127.0.0.1
  bindIp: 192.168.1.2
  #Communication token, please keep consistent with the WGTOKEN configured on the server side
  wgToken: wgcloud
mqtt:
  minTaskTopic: min-task
  agentInfoTopic: agent-info
  brokerUrl: tcp://185.183.182.195